### ISSUE TITLE
last commit issue

### ISSUE THREAD

**Issue by KirillTertunov** [authenio/samlify-xsd-schema-validator#4]
Hi, there.
After yesterday's commit there is an error. I checked an xml, it's valid.  
"@authenio/xsd-schema-validator": "0.7.1" and  "@authenio/samlify-xsd-schema-validator": "1.0.3" work correctly.
<img width="1215" alt="Screenshot 2023-05-12 at 09 52 04" src="https://github.com/authenio/samlify-xsd-schema-validator/assets/74527210/df7238b4-d832-4e71-b0fb-d6ef1c579a96">

**Comment by tngan** [comment]
@KirillTertunov DTD processing is disabled for security reasons, would you like to share the raw SAML document example here, remember to remove all sensitive information.

**Comment by KirillTertunov** [comment]
here you are
`
<samlp:Response xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"
  xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" Destination="https://my-sp/saml/consume" ID="ID_" IssueInstant="2023-05-12T06:18:32.654Z" Version="2.0">
  <saml:Issuer>https://myIdp/realms/sso</saml:Issuer>
  <dsig:Signature xmlns:dsig="http://www.w3.org/2000/09/xmldsig#">
    <dsig:SignedInfo>
      <dsig:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
      <dsig:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/>
      <dsig:Reference URI="#ID_0b17dac8-....">
        <dsig:Transforms>
          <dsig:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
          <dsig:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
        </dsig:Transforms>
        <dsig:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
        <dsig:DigestValue>DigestValue</dsig:DigestValue>
      </dsig:Reference>
    </dsig:SignedInfo>
    <dsig:SignatureValue>signature value</dsig:SignatureValue>
    <dsig:KeyInfo>
      <dsig:X509Data>
        <dsig:X509Certificate>my cert</dsig:X509Certificate>
      </dsig:X509Data>
    </dsig:KeyInfo>
  </dsig:Signature>
  <samlp:Status>
    <samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success"/>
  </samlp:Status>
  <saml:Assertion xmlns="urn:oasis:names:tc:SAML:2.0:assertion" ID="ID_...." IssueInstant="2023-05-12T06:18:32.654Z" Version="2.0">
    <saml:Issuer>https://myIdp/realms/sso</saml:Issuer>
    <saml:Subject>
      <saml:NameID Format="urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress">test@gmail.com</saml:NameID>
      <saml:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
        <saml:SubjectConfirmationData NotOnOrAfter="2023-05-12T06:23:30.654Z" Recipient="https://my-sp/saml/consume"/>
      </saml:SubjectConfirmation>
    </saml:Subject>
    <saml:Conditions NotBefore="2023-05-12T06:18:30.654Z" NotOnOrAfter="2023-05-12T06:19:30.654Z">
      <saml:AudienceRestriction>
        <saml:Audience>name</saml:Audience>
      </saml:AudienceRestriction>
    </saml:Conditions>
    <saml:AuthnStatement AuthnInstant="2023-05-12T06:18:32.654Z" SessionIndex="index" SessionNotOnOrAfter="2023-05-12T16:18:32.654Z">
      <saml:AuthnContext>
        <saml:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:unspecified</saml:AuthnContextClassRef>
      </saml:AuthnContext>
    </saml:AuthnStatement>
    <saml:AttributeStatement>
      <saml:Attribute Name="Role" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic">
        <saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">offline_access</saml:AttributeValue>
      </saml:Attribute>
      <saml:Attribute Name="Role" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic">
        <saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">uma_authorization</saml:AttributeValue>
      </saml:Attribute>
      <saml:Attribute Name="Role" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic">
        <saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">view-profile</saml:AttributeValue>
      </saml:Attribute>
      <saml:Attribute Name="Role" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic">
        <saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">manage-account</saml:AttributeValue>
      </saml:Attribute>
      <saml:Attribute Name="Role" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic">
        <saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">default-roles-ssodevelop</saml:AttributeValue>
      </saml:Attribute>
      <saml:Attribute Name="Role" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic">
        <saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">manage-account-links</saml:AttributeValue>
      </saml:Attribute>
    </saml:AttributeStatement>
  </saml:Assertion>
</samlp:Response>`

**Comment by romroux** [comment]
Same problem here, 
I noticed DTD are specified in some xsd schema files (for example https://github.com/authenio/samlify-xsd-schema-validator/blob/master/schemas/xmldsig-core-schema.xsd), could it be the source of the issue ?

**Comment by romroux** [comment]
Hello, 

Same here, we're using openjdk11

By setting sf.setFeature("http://apache.org/xml/features/disallow-doctype-decl", true) isn't it a problem to import xsd files with a DOCTYPE as in xmldsig-core-schema.xsd and xenc-schema.xsd ?

https://xerces.apache.org/xerces2-j/features.html#disallow-doctype-decl seems to explain that a fatal error is thrown if the document contains a DOCTYPE declaration

**Comment by tngan** [comment]
@romroux Good catch, it's about the xsd file that we are applying, I am not sure if it is okay to whitelist the xsd files.

**Comment by romroux** [comment]
As DTD is now disabled, the DOCTYPE comment should no longer be needed. If leaving it seems to cause this issue, maybe you just need to comment it out in those two files. But I must admit I am no expert about saml, xml or dtd

**Comment by youssefoukh** [comment]
Hello
I have the same error above on the first comment on version 1.0.2 and although I switched to 1.0.4 I still get the same error.
>[ERROR] validateXML Error: invalid xml (status=FATAL_ERROR)
	[fatal] Feature 'http://xml.org/sax/features/external-general-entities' is not recognized.
    at buildError (/var/app/current/node_modules/@authenio/xsd-schema-validator/lib/validator.js:126:12)
    at finish (/var/app/current/node_modules/@authenio/xsd-schema-validator/lib/validator.js:92:34)
    at ChildProcess.<anonymous> (/var/app/current/node_modules/@authenio/xsd-schema-validator/lib/validator.js:132:5)
    at ChildProcess.emit (events.js:314:20)
    at ChildProcess.EventEmitter.emit (domain.js:483:12)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)

Any recommendation please on how to fix this?
Thank you.

**Comment by tngan** [comment]
@youssefoukh Please update to v1.0.5 and proceed the testing.

**Comment by youssefoukh** [comment]
Hello 
It works now thank you for the help 👍

**Comment by tngan** [comment]
@KirillTertunov @romroux @youssefoukh I will close this issue first, please update to v1.0.5.
